apiVersion: apps/v1
kind: Deployment
metadata:
  name: calico-apiserver
spec:
  template:
    spec:
      volumes:
        - name: calico-apiserver-certs
          secret:
            secretName: calico-apiserver-certs
            items:
              - key: ca.crt
                path: ca.crt
              - key: tls.crt
                path: apiserver.crt
              - key: tls.key
                path: apiserver.key
