# Adds missing apiserver Calico CRD permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-crds-addon
  labels:
    rbac.authorization.k8s.io/aggregate-to-calico-crds: "true"
rules:
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - stagedglobalnetworkpolicies
      - stagednetworkpolicies
      - stagedkubernetesnetworkpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
