apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v3.projectcalico.org
  annotations:
    cert-manager.io/inject-ca-from: kube-system/calico-apiserver-cert
spec:
  service:
    name: calico-api
    namespace: kube-system
    port: 443
