kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
spec:
  template:
    spec:
      containers:
        - name: calico-node
          env:
            # Use `sv -w 60 1 felix` inside the container to get a profile
            - name: FELIX_DebugMemoryProfilePath
              value: "/tmp/felix-mem.pb.gz"
          resources:
            requests:
              cpu: 250m
              memory: 200Mi
            limits:
              cpu: 2000m
              memory: 1Gi
