kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node-bpf
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: calico-node
          env:
            # Use `sv -w 60 1 felix` inside the container to get a profile
            - name: FELIX_DebugMemoryProfilePath
              value: "/tmp/felix-mem.pb.gz"
            - name: IP_AUTODETECTION_METHOD
              value: kubernetes-internal-ip
