kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
spec:
  template:
    spec:
      initContainers:
        - name: install-cni
          env:
            # Use Kubernetes service host and port as specified in calico config
            # (configMap) to avoid relying on kube-proxy mechanisms. We need
            # this since we run kube-proxy as a calico sidecar and since v3.23
            # calico init needs to query the apiserver. Thus, in fresh nodes it
            # will not be able to route requests to apiservers until kube-proxy
            # is up and running.
            - name: KUBERNETES_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: kubernetes_service_host
                  name: calico-config
            - name: KUBERNETES_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: kubernetes_service_port
                  name: calico-config
