apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiserver-certificate.yaml
  - apiserver-pdb.yaml
  - apiserver.yaml
  - calico-typha.yaml
  - felix-metrics-svc.yaml
patchesStrategicMerge:
  - calico-env-patch.yaml
  - calico-init-patch.yaml
  - calico-resources-patch.yaml
  - apiserver-patch.yaml
