apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiserver-certificate.yaml
  - apiserver-pdb.yaml
  - apiserver.yaml
  - calico-bpf.yaml
  - felix-metrics-svc.yaml
patchesStrategicMerge:
  - calico-patch.yaml
  - apiserver-patch.yaml
