apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiserver-certificate.yaml
  - apiserver-pdb.yaml
  - apiserver-rbac-pacth.yaml
  - apiserver.yaml
  - calico-typha-metrics-service.yaml
  - calico-typha.yaml
  - felix-metrics-svc.yaml
patches:
  - path: apiserver-apiservice.yaml
  - path: apiserver-args.yaml
  - path: apiserver-certificate-secret-patch.yaml
  - path: apiserver-clusterrolebindings.yaml
  - path: apiserver-rolling-strategy.yaml
  - path: calico-clusterrolebindings.yaml
  - path: calico-delete-ipam-upgrade.yaml
  - path: calico-env-patch.yaml
  - path: calico-init-patch.yaml
  - path: calico-resources-patch.yaml
  - path: calico-typha-metrics-patch.yaml
  - path: calico-typha-node-selector.yaml
